common: avoid [redundant-cast] warning in _parse_json_list()
mypy 1.16 now better detects the type, which leads to a [redundant-cast]
warning:

  common.py:294: error: Redundant cast to "list[Any]"  [redundant-cast]

Older versions couldn't figure that out, so the type was Any and we
needed the cast to avoid "[no-any-return]":

  error: Returning Any from function declared to return "list[Any]"  [no-any-return]

Add another workaround for the issue, which should work with older and
newer mypy.