bmc: fix cyclic dependency between "bmc" and "host" modules
  $ python -c 'import bmc'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "./cluster-deployment-automation/bmc.py", line 7, in <module>
      import host
    File "./cluster-deployment-automation/host.py", line 12, in <module>
      from bmc import BMC
  ImportError: cannot import name 'BMC' from partially initialized module 'bmc' (most likely due to a circular import) (./cluster-deployment-automation/bmc.py)