Remove existing kernel-modules if needed
Encountered the following error which would result in an infinite loop
without any error output.

sudo rpm-ostree override replace working_dir/*.rpm
Checking out tree 1441bb2... done
No enabled rpm-md repositories.
Importing rpm-md... done
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: package kernel-modules-core-5.14.0-282.el9.aarch64 requires kernel-uname-r = 5.14.0-282.el9.aarch64, but none of the providers can be installed
  - cannot install both kernel-core-4.18.0-372.35.1.el8_6.mr3440_221116_1544.aarch64 and kernel-core-5.14.0-282.el9.aarch64
  - conflicting requests

Signed-off-by: Salvatore Daniele <sdaniele@redhat.com>