extraConfigSriov: fail early on missing podman permissions to build sriov_network_operator
With `sriov_network_operator_local:True` we build a container from git.
That requires to fetch a build dependency from
registry.ci.openshift.org, which requires authentication.

It's an easy mistake to make, to forget to authenticate. Or the login
token can expire.

If we only notice the problem when trying to build the container, we
already wasted an hour to deploy the cluster. We need to check early,
whether we have permissions.

Now we get:

    # ./cda.py /root/cluster2.yaml deploy
    2024-05-22 09:08:31 INFO [th:140215444772672]: range = ('192.168.122.1', '192.168.122.7')
    Traceback (most recent call last):
      File "/root/cluster-deployment-automation/./cda.py", line 82, in <module>
        main()
      File "/root/cluster-deployment-automation/./cda.py", line 76, in main
        main_deploy(args)
      File "/root/cluster-deployment-automation/./cda.py", line 17, in main_deploy
        cc = ClustersConfig(args.config, args.worker_range)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/cluster-deployment-automation/clustersConfig.py", line 272, in __init__
        c.pre_check()
      File "/root/cluster-deployment-automation/clustersConfig.py", line 59, in pre_check
        raise ValueError("Building sriov_network_operator requires permissions to fetch. Get a token from https://oauth-openshift.apps.ci.l2s4.p1.openshiftapps.com/oauth/token/request and issue `podman login registry.ci.openshift.org`")
    ValueError: Building sriov_network_operator requires permissions to fetch. Get a token from https://oauth-openshift.apps.ci.l2s4.p1.openshiftapps.com/oauth/token/request and issue `podman login registry.ci.openshift.org`