coreosBuilder: fix build() to initialize git submodule
fedora-coreos-config has a git submodule "fedora-bootc". This needs to
be initialized, otherwise the build is going to fail:

  # podman run --rm -ti --userns=host -u root --privileged -v /tmp/build/fcos:/srv/ --device /dev/kvm --device /dev/fuse --tmpfs /tmp -v /var/tmp:/var/tmp --name cosa -v /tmp/build/fedora-coreos-config:/git:ro quay.io/coreos-assembler/coreos-assembler:latest fetch
  Config commit: 9aebe7895a1f2055569ebc670a2212319c106d1a
  Using manifest: /srv/src/config/manifest.yaml
  error: Can't open file "/srv/src/config/manifests/../fedora-bootc/minimal-plus/manifest.yaml" for reading: No such file or directory (os error 2)
  failed to execute cmd-fetch: exit status 1

It is not clear to me how this ever worked. Fix this by initializing the
submodules.