Handle case when virsh network does not yet exist
The first time we run CDA on a freshly installed cluster, the default
network may not exist yet.

i.e.

error: failed to connect to the hypervisor
error: Operation not supported: Cannot use direct socket mode if no URI is set. For more information see https://libvirt.org/kbase/failed_connection_after_install
.html

This will cause the following to fail:

"""
xml_str = hostconn.run("virsh net-dumpxml default").out
tree = et.fromstring(xml_str)
"""

Signed-off-by: Salvatore Daniele <sdaniele@redhat.com>