flake8: fix "F811 redefinition of unused 'os' from line 1" warning
  $ flake8 --select F811
  ./clusterDeployer.py:27:1: F811 redefinition of unused 'os' from line 1