Prevent ACC boot issue mentioning DRAM interface
Addresses IIC-640.
Error: Timed out while waiting for response from the shared DRAM interface. Stopping boot.

At one point, we were advised to set the init_app_acc_nboot_stage option to 2.
This guidance has changed to 0, this makes the IMC wait a little bit longer
before trying to start the ACC.